version: 0.2
phases:
  install:
    commands:
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - npx ng build --prod
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/hello-word'  # ← Replace with your actual dist folder name
